# Edit `app` to your chosen name, or let `fly launch` generate it.
app = "my-ytdl"
primary_region = "iad"

[build]

[env]
  DATA_DIR = "/data"
  PORT = "8080"
  CONCURRENCY = "2"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "ytdl_data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
